### ISSUE TITLE
switch替换方案请教

### ISSUE THREAD

**Issue by ldwstyle** [SmallStoneSK/react-router-animation-demo#1]
```
<Switch location={location}>
          {RouterConfig.map((config, index) => (
            <Route exact key={index} {...config}/>
          ))}
  </Switch>
```

博主源码使用了Switch 来解决匹配相同界面的问题，如果不使用Switch如何解决呢？（路由我使用了react-keeper，并没有react-router中的switch）
谢谢！

**Comment by SmallStoneSK** [comment]
@ldwstyle 没用过react-keeper，不知道它内部的工作原理是怎么样的。

要解决这个问题，其实关键是在于如何匹配页面的路由。Switch只是保证在众多routes中匹配第一个匹配上的，而且要是location设置不正确，过渡效果也是错的。

由于TransitionGroup会将children保存至它的state中，所以当新旧Page发生变化时，会有两个Page同时存在。如果你想过渡过程正常，你得保证旧页面匹配的路由这时不受新的location影响。

具体代码如何实现，可能你需要稍微看下react-keeper的内部实现，关键还是在于匹配的规则。

**Comment by ldwstyle** [comment]
@SmallStoneSK 
再请教您一个问题，在博主的例子中：
从HomePage进入ListPage，HomePage会保留一段时间再消失，ListPage正常渲染，为什么Homepage会保留一段时间？完全是switch来控制的吗？为什么switch能让Homepage保留一段时间？
如果把switch替换成div ，从HomePage进入ListPage，会直接渲染两个ListPage，Homepage并不会保留一段时间，而是直接消失。为什么这个时候Homepage不会保留一段时间，而是其中的一个ListPage保留一段时间再消失？

谢谢！

**Comment by SmallStoneSK** [comment]
@ldwstyle 
不是Switch控制的，是TransitionGroup来控制的，你可以具体看[文章](https://github.com/SmallStoneSK/Blog/issues/8/)的4.2小节，我有在文章中解释。

你也可以直接看[源码](https://github.com/reactjs/react-transition-group/blob/master/src/TransitionGroup.js#L62)，它会保存旧的节点，在旧节点完全退出的时候，才卸载旧节点。

Switch组件是根据location来匹配路由的，如果用前后两个不同的location匹配得到不同的路由组件，就能保留两个page。
