### ISSUE TITLE
手势左右滑动切换页面,动画异常

### ISSUE THREAD

**Issue by darkfiredarkhalo** [SmallStoneSK/react-router-animation-demo#3]
怎么对手势和浏览器前进后退做一下处理?手势的话,动画会多余;浏览器的话,前进和后退的action都是pop,动画错误

**Comment by SmallStoneSK** [comment]
@darkfiredarkhalo 

额，这方面不太清楚，没有做过，你可以搜索其他的一些资料调研看看。。
